package duke.commands;

import java.io.IOException;
import java.util.ArrayList;

import duke.Storage;
import duke.TaskList;
import duke.Ui;

/**
 * Represents the Bye Command for Duke, termination of program.
 *
 * @author MrTwit99
 * @since 2023-02-07
 */
public class ByeCommand implements Command {

    /**
     * Returns the String message that is to be displayed to the user during termination of the program.
     *
     * @param parsedCmd ArrayList of String type that contains parsed information about the task description and
     *                  status generated by Parser.parse().
     * @param tasks Duke's TaskList object that stores all Tasks objects.
     * @param storage Duke's Storage object to allow file access.
     * @param ui Duke's Ui object to display and print messages to the user. Acts as a screen.
     * @return String message of termination of program.
     */
    @Override
    public String execute(ArrayList<String> parsedCmd, TaskList tasks, Storage storage, Ui ui) {
        try {
            return ui.showFarewellMessage();
        } catch (IOException e) {
            return e.getMessage();
        }
    }
}
