package duke.commands;

import java.io.IOException;
import java.util.ArrayList;

import duke.Storage;
import duke.TaskList;
import duke.Ui;

/**
 * Represents the Help Command for Duke, directs user to User Guide for more info on help.
 *
 * @author MrTwit99
 * @since 2023-02-14
 */
public class HelpCommand implements Command {

    /**
     * Returns the String message containing an URL link to the User Guide to aid users in their troubleshooting etc.
     *
     * @param parsedCmd ArrayList of String type that contains parsed information about the task description and
     *                  status generated by Parser.parse().
     * @param tasks Duke's TaskList object that stores all Tasks objects.
     * @param storage Duke's Storage object to allow file access.
     * @param ui Duke's Ui object to display and print messages to the user. Acts as a screen.
     * @return String message containing an URL link to the User Guide
     */
    @Override
    public String execute(ArrayList<String> parsedCmd, TaskList tasks, Storage storage, Ui ui) {
        try {
            return ui.showHelpMessage();
        } catch (IOException e) {
            return e.getMessage();
        }
    }
}
