package domain.entities.taskmanager;

import domain.entities.core.Serializable;

import java.util.Map;

/**
 * This shall resemble a Task. The reason that no modifiers was added was
 * because this class shall be package private.
 */
public abstract class Task implements Serializable {
    /**
     * Creates a new Task instance.
     * @param name the name of the list item.
     * @param isComplete if the Task is complete or not.
     */
    Task(String name, boolean isComplete) {
        this.name = name;
        this.isComplete = isComplete;
    }

    /**
     * Initializes a new Task instance, with its isComplete set to false.
     * @param name the name of the Task instance.
     */
    Task(String name) {
        this(name, false);
    }

    /**
     * The name of the list item.
     *
     * It is set to final now as we do not allow the change of names for now.
     */
    private final String name;

    /**
     * If the object is complete or not.
     */
    private boolean isComplete;

    /**
     * Sets the isComplete to complete.
     * @param complete the value to set the isComplete to.
     */
    public void setComplete(boolean complete) {
        isComplete = complete;
    }

    /**
     * Toggles the isComplete value, i.e. if it were true, then set it to false;
     * if it were false, then set it to true.
     */
    public void toggleIsComplete() {
       isComplete = !isComplete;
    }

    /**
     * The key for identifying if the object is marked as complete or not.
     */
    protected static final String completeKey = "/complete";


    /**
     * Retrieving the isComplete value from the map.
     * @param map the map generated by the TokenUtilities.
     * @return true if the map contains the key and the value is true, false
     * otherwise.
     */
    protected static boolean getIsComplete(Map<String, String> map) {
        if (map.get(completeKey) != null) {
            return map.get(completeKey).equals("true");
        } else {
            return false;
        }
    }

    @Override
    public String serialize() {
        if (isComplete) {
            return name + " " + completeKey + " true";
        } else {
            return name;
        }
    }

    @Override
    public String toString() {
        String prefix;
        if (isComplete) {
            prefix = "[x] ";
        } else {
            prefix = "[ ] ";
        }
        return prefix + name;
    }
}
