package duke;

import java.io.File;
import java.io.IOException;

import duke.command.Command;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.image.Image;


/**
 * The Duke program implements a 'to-do' list
 * where users can add, mark and delete tasks.
 */

public class Duke {

    private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));
    private Image duke = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png"));

    private Tasklist tasklist = new Tasklist();
    private int saveNo = 1;

    /**
     * Generates a response accordingly
     * to the user input.
     *
     * @param input The string inputed by the user.
     *
     * @return The response generated by duke.
     */
    @FXML
    public String getResponse(String input) {

        try {
            saveNo = Storage.getCurrentSaveNumber();
            File saveFile = new File("duke" + saveNo + ".txt");
            if (saveFile.createNewFile()) {
                System.out.println("Save file created: " + saveFile.getName());
            } else {
                tasklist = Storage.load(saveNo);
            }
            Command command = Parser.parseInput(input);
            String output = command.execute(tasklist, saveNo);
            if (command.isExit()) {
                Platform.exit();
            }
            return output;
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "An error occured";
    }
}
